export type ModelCategory = "text" | "image" | "video" | "audio" | "code";

export interface AIModel {
  id: string;
  name: string;
  provider: string;
  category: ModelCategory;
  description: string;
  pricing: string;
  pricingUnit: string;
  speed: "fast" | "medium" | "slow";
  quality: "standard" | "high" | "premium";
  context?: string;
  featured?: boolean;
}

export const models: AIModel[] = [
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    category: "text",
    description: "Most capable multimodal model. Excellent reasoning, vision, and speed.",
    pricing: "$2.50",
    pricingUnit: "/ 1M input tokens",
    speed: "fast",
    quality: "premium",
    context: "128K",
    featured: true,
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "OpenAI",
    category: "text",
    description: "Affordable and intelligent small model for fast, lightweight tasks.",
    pricing: "$0.15",
    pricingUnit: "/ 1M input tokens",
    speed: "fast",
    quality: "high",
    context: "128K",
  },
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    category: "text",
    description: "Best-in-class coding and analysis. Strong instruction following.",
    pricing: "$3.00",
    pricingUnit: "/ 1M input tokens",
    speed: "fast",
    quality: "premium",
    context: "200K",
    featured: true,
  },
  {
    id: "claude-3-haiku",
    name: "Claude 3 Haiku",
    provider: "Anthropic",
    category: "text",
    description: "Fastest and most compact model for near-instant responsiveness.",
    pricing: "$0.25",
    pricingUnit: "/ 1M input tokens",
    speed: "fast",
    quality: "standard",
    context: "200K",
  },
  {
    id: "gemini-2-flash",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    category: "text",
    description: "Ultra-fast multimodal model with massive context window.",
    pricing: "$0.10",
    pricingUnit: "/ 1M input tokens",
    speed: "fast",
    quality: "high",
    context: "1M",
    featured: true,
  },
  {
    id: "llama-3-3-70b",
    name: "Llama 3.3 70B",
    provider: "Meta",
    category: "text",
    description: "Open-weight powerhouse. Strong performance at competitive price.",
    pricing: "$0.40",
    pricingUnit: "/ 1M input tokens",
    speed: "medium",
    quality: "high",
    context: "128K",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    category: "text",
    description: "Exceptional reasoning and coding at a fraction of the cost.",
    pricing: "$0.27",
    pricingUnit: "/ 1M input tokens",
    speed: "fast",
    quality: "high",
    context: "64K",
  },
  {
    id: "mistral-large",
    name: "Mistral Large",
    provider: "Mistral",
    category: "text",
    description: "Top-tier European model with excellent multilingual support.",
    pricing: "$2.00",
    pricingUnit: "/ 1M input tokens",
    speed: "medium",
    quality: "premium",
    context: "128K",
  },
  {
    id: "dall-e-3",
    name: "DALL·E 3",
    provider: "OpenAI",
    category: "image",
    description: "Highly detailed image generation with strong prompt adherence.",
    pricing: "$0.040",
    pricingUnit: "/ image (1024×1024)",
    speed: "medium",
    quality: "premium",
    featured: true,
  },
  {
    id: "flux-pro",
    name: "FLUX.1 Pro",
    provider: "Black Forest Labs",
    category: "image",
    description: "State-of-the-art photorealistic and artistic image generation.",
    pricing: "$0.055",
    pricingUnit: "/ image",
    speed: "medium",
    quality: "premium",
    featured: true,
  },
  {
    id: "flux-schnell",
    name: "FLUX.1 Schnell",
    provider: "Black Forest Labs",
    category: "image",
    description: "Lightning-fast generation optimized for speed and iteration.",
    pricing: "$0.003",
    pricingUnit: "/ image",
    speed: "fast",
    quality: "high",
  },
  {
    id: "stable-diffusion-3",
    name: "Stable Diffusion 3",
    provider: "Stability AI",
    category: "image",
    description: "Open model with excellent text rendering and composition.",
    pricing: "$0.035",
    pricingUnit: "/ image",
    speed: "medium",
    quality: "high",
  },
  {
    id: "midjourney-v6",
    name: "Midjourney v6",
    provider: "Midjourney",
    category: "image",
    description: "Artistic excellence. Unmatched aesthetic quality and style control.",
    pricing: "$0.08",
    pricingUnit: "/ image",
    speed: "slow",
    quality: "premium",
  },
  {
    id: "runway-gen3",
    name: "Runway Gen-3 Alpha",
    provider: "Runway",
    category: "video",
    description: "Cinematic video generation from text or image prompts.",
    pricing: "$0.05",
    pricingUnit: "/ second",
    speed: "slow",
    quality: "premium",
    featured: true,
  },
  {
    id: "luma-dream-machine",
    name: "Luma Dream Machine",
    provider: "Luma AI",
    category: "video",
    description: "High-quality video with realistic motion and physics.",
    pricing: "$0.04",
    pricingUnit: "/ second",
    speed: "medium",
    quality: "high",
  },
  {
    id: "kling-1-5",
    name: "Kling 1.5",
    provider: "Kuaishou",
    category: "video",
    description: "Long-form video generation with strong temporal consistency.",
    pricing: "$0.03",
    pricingUnit: "/ second",
    speed: "medium",
    quality: "high",
  },
  {
    id: "sora",
    name: "Sora",
    provider: "OpenAI",
    category: "video",
    description: "Frontier video model capable of complex scenes and physics.",
    pricing: "$0.10",
    pricingUnit: "/ second",
    speed: "slow",
    quality: "premium",
  },
  {
    id: "whisper-v3",
    name: "Whisper Large v3",
    provider: "OpenAI",
    category: "audio",
    description: "Industry-standard speech-to-text with high accuracy.",
    pricing: "$0.006",
    pricingUnit: "/ minute",
    speed: "fast",
    quality: "premium",
  },
  {
    id: "eleven-multilingual",
    name: "ElevenLabs Multilingual v2",
    provider: "ElevenLabs",
    category: "audio",
    description: "Ultra-realistic text-to-speech in 29 languages.",
    pricing: "$0.18",
    pricingUnit: "/ 1K characters",
    speed: "fast",
    quality: "premium",
    featured: true,
  },
  {
    id: "openai-tts",
    name: "OpenAI TTS HD",
    provider: "OpenAI",
    category: "audio",
    description: "Natural-sounding speech synthesis with multiple voices.",
    pricing: "$0.015",
    pricingUnit: "/ 1K characters",
    speed: "fast",
    quality: "high",
  },
  {
    id: "deepgram-nova",
    name: "Deepgram Nova-2",
    provider: "Deepgram",
    category: "audio",
    description: "Real-time transcription with industry-leading accuracy.",
    pricing: "$0.0043",
    pricingUnit: "/ minute",
    speed: "fast",
    quality: "high",
  },
  {
    id: "codestral",
    name: "Codestral",
    provider: "Mistral",
    category: "code",
    description: "Specialized code model. Strong fill-in-the-middle and completion.",
    pricing: "$0.20",
    pricingUnit: "/ 1M input tokens",
    speed: "fast",
    quality: "high",
    context: "32K",
  },
  {
    id: "deepseek-coder-v2",
    name: "DeepSeek Coder V2",
    provider: "DeepSeek",
    category: "code",
    description: "Exceptional coding performance across 338 languages.",
    pricing: "$0.14",
    pricingUnit: "/ 1M input tokens",
    speed: "fast",
    quality: "premium",
    context: "128K",
    featured: true,
  },
  {
    id: "gpt-4o-code",
    name: "GPT-4o (Code)",
    provider: "OpenAI",
    category: "code",
    description: "General-purpose model tuned for complex software engineering.",
    pricing: "$2.50",
    pricingUnit: "/ 1M input tokens",
    speed: "fast",
    quality: "premium",
    context: "128K",
  },
];

export const categoryLabels: Record<ModelCategory, string> = {
  text: "Text / Chat",
  image: "Image Generation",
  video: "Video",
  audio: "Audio / Voice",
  code: "Code",
};

export const categoryIcons: Record<ModelCategory, string> = {
  text: "MessageSquare",
  image: "Image",
  video: "Video",
  audio: "Mic",
  code: "Code2",
};
